import type { QuizBankEntry } from "./quiz.types";

/** 10 real technology quizzes — easy → hard, 10–50 coins. Synced to DB on server start. */
export const QUIZ_BANK: QuizBankEntry[] = [
  {
    id: "seed_qz_01",
    community_slug: "programming",
    title: "Computer & Tech Basics",
    description: "Hardware, browsers, files, and everyday tech — perfect for beginners.",
    difficulty: "easy",
    minutes: 5,
    coins: 10,
    questions: [
      { id: "q1", type: "mcq", prompt: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Power Utility", "Core Program Unit"], answer: 0 },
      { id: "q2", type: "true_false", prompt: "RAM stores data temporarily while your computer is running.", answer: true },
      { id: "q3", type: "mcq", prompt: "Which device is used to browse websites?", options: ["Spreadsheet", "Web browser", "Calculator", "Printer driver"], answer: 1 },
      { id: "q4", type: "mcq", prompt: "A URL is best described as:", options: ["A web address", "A type of virus", "A keyboard shortcut", "A file format only"], answer: 0 },
      { id: "q5", type: "true_false", prompt: "Wi-Fi and the internet are exactly the same thing.", answer: false },
      { id: "q6", type: "multi", prompt: "Select input devices:", options: ["Keyboard", "Monitor", "Mouse", "Speaker"], answer: [0, 2] },
      { id: "q7", type: "mcq", prompt: "Which stores files long-term?", options: ["RAM", "Cache", "SSD / hard drive", "CPU register"], answer: 2 },
      { id: "q8", type: "true_false", prompt: "Restarting an app or device can fix many common software glitches.", answer: true },
    ],
  },
  {
    id: "seed_qz_02",
    community_slug: "programming",
    title: "JavaScript Essentials",
    description: "Variables, types, async, and modern JS patterns every developer should know.",
    difficulty: "easy",
    minutes: 8,
    coins: 15,
    questions: [
      { id: "q1", type: "mcq", prompt: "Which keyword declares a block-scoped variable?", options: ["var", "let", "function", "define"], answer: 1 },
      { id: "q2", type: "true_false", prompt: "JavaScript is single-threaded for executing user code.", answer: true },
      { id: "q3", type: "mcq", prompt: "What does `===` compare?", options: ["Value only", "Value and type", "Reference only", "Truthy values"], answer: 1 },
      { id: "q4", type: "mcq", prompt: "Which method adds an item to the end of an array?", options: ["push", "pop", "shift", "slice"], answer: 0 },
      { id: "q5", type: "true_false", prompt: "`null` and `undefined` are identical in JavaScript.", answer: false },
      { id: "q6", type: "multi", prompt: "Select all primitive types in JavaScript:", options: ["string", "object", "boolean", "symbol"], answer: [0, 2, 3] },
      { id: "q7", type: "mcq", prompt: "Async/await is built on top of:", options: ["Callbacks", "Promises", "Web Workers", "Generators only"], answer: 1 },
      { id: "q8", type: "mcq", prompt: "JSON.parse throws if the string is:", options: ["Empty", "Invalid JSON", "A number", "An array"], answer: 1 },
    ],
  },
  {
    id: "seed_qz_03",
    community_slug: "cloud",
    title: "Git & DevOps Basics",
    description: "Version control, branches, CI/CD, and deployment workflows.",
    difficulty: "easy",
    minutes: 8,
    coins: 20,
    questions: [
      { id: "q1", type: "mcq", prompt: "git commit saves changes to:", options: ["Remote only", "Local repository", "Cloud automatically", "package.json"], answer: 1 },
      { id: "q2", type: "true_false", prompt: "A branch lets you work on features in isolation.", answer: true },
      { id: "q3", type: "mcq", prompt: "git pull typically:", options: ["Pushes only", "Fetches and merges", "Deletes branch", "Tags release"], answer: 1 },
      { id: "q4", type: "mcq", prompt: ".gitignore tells Git to:", options: ["Ignore certain files", "Encrypt secrets", "Run tests", "Deploy app"], answer: 0 },
      { id: "q5", type: "true_false", prompt: "Merge conflicts happen when the same lines changed differently.", answer: true },
      { id: "q6", type: "multi", prompt: "CI/CD pipelines often include:", options: ["Automated tests", "Build step", "Manual fax", "Deploy to staging"], answer: [0, 1, 3] },
      { id: "q7", type: "mcq", prompt: "Docker packages apps with:", options: ["Only source code", "Dependencies + runtime in containers", "DNS records", "SSL certs only"], answer: 1 },
      { id: "q8", type: "mcq", prompt: "Environment variables are used for:", options: ["UI colors only", "Config and secrets", "Git history", "Image compression"], answer: 1 },
    ],
  },
  {
    id: "seed_qz_04",
    community_slug: "programming",
    title: "Python for Developers",
    description: "Syntax, data structures, and common patterns in Python 3.",
    difficulty: "medium",
    minutes: 8,
    coins: 25,
    questions: [
      { id: "q1", type: "mcq", prompt: "Which creates a list in Python?", options: ["{1,2}", "(1,2)", "[1,2]", "<1,2>"], answer: 2 },
      { id: "q2", type: "true_false", prompt: "Python lists are mutable.", answer: true },
      { id: "q3", type: "mcq", prompt: "List comprehension: [x*2 for x in range(3)] equals:", options: ["[0,2,4]", "[2,4,6]", "[1,2,3]", "[0,1,2]"], answer: 0 },
      { id: "q4", type: "mcq", prompt: "Which keyword defines a function?", options: ["func", "def", "fn", "function"], answer: 1 },
      { id: "q5", type: "true_false", prompt: "Tuples can be used as dictionary keys if they contain only immutable items.", answer: true },
      { id: "q6", type: "multi", prompt: "Select valid ways to open a file for reading:", options: ["open('f.txt','r')", "with open('f.txt') as f:", "readfile('f.txt')", "open('f.txt', encoding='utf-8')"], answer: [0, 1, 3] },
      { id: "q7", type: "mcq", prompt: "`len()` on a dictionary returns:", options: ["Number of keys", "Memory size", "Longest key", "Hash value"], answer: 0 },
      { id: "q8", type: "mcq", prompt: "Virtual environments help with:", options: ["Faster CPU", "Isolated dependencies", "GPU access", "Syntax highlighting"], answer: 1 },
    ],
  },
  {
    id: "seed_qz_05",
    community_slug: "programming",
    title: "React & Web Basics",
    description: "Components, hooks, state, and how modern web apps are built.",
    difficulty: "medium",
    minutes: 10,
    coins: 30,
    questions: [
      { id: "q1", type: "mcq", prompt: "React components return:", options: ["DOM nodes directly", "JSX describing UI", "CSS only", "SQL queries"], answer: 1 },
      { id: "q2", type: "true_false", prompt: "useState can store any JavaScript value.", answer: true },
      { id: "q3", type: "mcq", prompt: "Which hook runs side effects?", options: ["useMemo", "useEffect", "useRef", "useId"], answer: 1 },
      { id: "q4", type: "mcq", prompt: "Keys in lists help React:", options: ["Style faster", "Identify changed items", "Minify bundles", "Cache images"], answer: 1 },
      { id: "q5", type: "true_false", prompt: "Props flow from parent to child and should not be mutated by the child.", answer: true },
      { id: "q6", type: "multi", prompt: "Select client-side routing benefits:", options: ["No full page reload", "Shareable URLs", "No JavaScript needed", "Faster in-app navigation"], answer: [0, 1, 3] },
      { id: "q7", type: "mcq", prompt: "Controlled inputs tie value to:", options: ["localStorage", "React state", "Cookies", "URL hash"], answer: 1 },
      { id: "q8", type: "mcq", prompt: "Vite is primarily a:", options: ["Database", "Build tool / dev server", "CSS framework", "Testing library"], answer: 1 },
    ],
  },
  {
    id: "seed_qz_06",
    community_slug: "data",
    title: "SQL & Databases",
    description: "Queries, joins, indexes, and relational data fundamentals.",
    difficulty: "medium",
    minutes: 10,
    coins: 35,
    questions: [
      { id: "q1", type: "mcq", prompt: "SELECT is used to:", options: ["Delete rows", "Read data", "Create tables", "Grant permissions"], answer: 1 },
      { id: "q2", type: "true_false", prompt: "A primary key must be unique per row.", answer: true },
      { id: "q3", type: "mcq", prompt: "INNER JOIN returns rows where:", options: ["Left table only", "Match exists in both tables", "All rows combined", "No duplicates ever"], answer: 1 },
      { id: "q4", type: "mcq", prompt: "WHERE filters rows:", options: ["Before grouping", "After ORDER BY", "Only on INSERT", "On indexes only"], answer: 0 },
      { id: "q5", type: "true_false", prompt: "An index always makes every query faster.", answer: false },
      { id: "q6", type: "multi", prompt: "ACID properties include:", options: ["Atomicity", "Availability", "Consistency", "Durability"], answer: [0, 2, 3] },
      { id: "q7", type: "mcq", prompt: "COUNT(*) counts:", options: ["Non-null values in one column", "All rows including nulls", "Distinct values only", "Indexes"], answer: 1 },
      { id: "q8", type: "mcq", prompt: "PostgreSQL is a:", options: ["NoSQL document store", "Relational database", "Cache", "Message queue"], answer: 1 },
    ],
  },
  {
    id: "seed_qz_07",
    community_slug: "cloud",
    title: "Cloud Computing 101",
    description: "IaaS, PaaS, scaling, and cloud architecture concepts.",
    difficulty: "medium",
    minutes: 10,
    coins: 40,
    questions: [
      { id: "q1", type: "mcq", prompt: "IaaS provides:", options: ["Ready-made SaaS apps", "Virtual machines & infra", "Only DNS", "Mobile SDKs"], answer: 1 },
      { id: "q2", type: "true_false", prompt: "Horizontal scaling adds more machines.", answer: true },
      { id: "q3", type: "mcq", prompt: "A load balancer:", options: ["Stores passwords", "Distributes traffic", "Compiles code", "Indexes SQL"], answer: 1 },
      { id: "q4", type: "mcq", prompt: "CDN helps by:", options: ["Caching content closer to users", "Replacing databases", "Writing tests", "Managing Git"], answer: 0 },
      { id: "q5", type: "true_false", prompt: "Serverless means zero servers exist anywhere.", answer: false },
      { id: "q6", type: "multi", prompt: "Good cloud security practices:", options: ["Least privilege IAM", "Public DB without password", "Encrypt data in transit", "Rotate secrets"], answer: [0, 2, 3] },
      { id: "q7", type: "mcq", prompt: "99.9% uptime allows roughly:", options: ["0 downtime", "~8.7 hours downtime/year", "1 day/month down", "No maintenance"], answer: 1 },
      { id: "q8", type: "mcq", prompt: "Object storage (S3-style) is best for:", options: ["Transactional SQL", "Files, images, backups", "CPU workloads", "In-memory cache only"], answer: 1 },
    ],
  },
  {
    id: "seed_qz_08",
    community_slug: "cybersec",
    title: "Cybersecurity Essentials",
    description: "OWASP basics, auth, encryption, and common attack vectors.",
    difficulty: "hard",
    minutes: 10,
    coins: 45,
    questions: [
      { id: "q1", type: "mcq", prompt: "SQL injection exploits:", options: ["Unsanitized queries", "CSS bugs", "DNS cache", "JPEG metadata"], answer: 0 },
      { id: "q2", type: "true_false", prompt: "HTTPS encrypts data in transit.", answer: true },
      { id: "q3", type: "mcq", prompt: "XSS allows attackers to:", options: ["Run scripts in victim browsers", "Format disks", "Change DNS TTL", "Mine Bitcoin on server"], answer: 0 },
      { id: "q4", type: "mcq", prompt: "Hashing passwords should use:", options: ["MD5 alone", "Salted slow hashes (bcrypt/argon2)", "Base64", "Reversible encryption"], answer: 1 },
      { id: "q5", type: "true_false", prompt: "Storing API keys in client-side code is safe if minified.", answer: false },
      { id: "q6", type: "multi", prompt: "OWASP Top 10 includes:", options: ["Broken access control", "Perfect hiring", "Injection", "Security misconfiguration"], answer: [0, 2, 3] },
      { id: "q7", type: "mcq", prompt: "2FA adds:", options: ["Second verification factor", "Second database", "Second CSS file", "Second domain"], answer: 0 },
      { id: "q8", type: "mcq", prompt: "Phishing typically uses:", options: ["Fake emails/links", "SQL joins", "GPU drivers", "Unit tests"], answer: 0 },
    ],
  },
  {
    id: "seed_qz_09",
    community_slug: "programming",
    title: "Data Structures & Algorithms",
    description: "Big-O, arrays, trees, graphs, and problem-solving basics.",
    difficulty: "hard",
    minutes: 12,
    coins: 48,
    questions: [
      { id: "q1", type: "mcq", prompt: "Array index access is typically:", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], answer: 0 },
      { id: "q2", type: "true_false", prompt: "A stack follows LIFO order.", answer: true },
      { id: "q3", type: "mcq", prompt: "Binary search requires:", options: ["Unsorted data", "Sorted data", "Linked list only", "Hash table"], answer: 1 },
      { id: "q4", type: "mcq", prompt: "Hash map average lookup is:", options: ["O(1)", "O(n²)", "O(n log n)", "O(log log n)"], answer: 0 },
      { id: "q5", type: "true_false", prompt: "BFS explores level by level in graphs.", answer: true },
      { id: "q6", type: "multi", prompt: "Linear data structures:", options: ["Array", "Tree", "Queue", "Graph"], answer: [0, 2] },
      { id: "q7", type: "mcq", prompt: "Merge sort time complexity is:", options: ["O(n log n)", "O(n)", "O(2^n)", "O(1)"], answer: 0 },
      { id: "q8", type: "mcq", prompt: "Dynamic programming avoids:", options: ["All loops", "Redundant subproblem work", "Using memory", "Input validation"], answer: 1 },
    ],
  },
  {
    id: "seed_qz_10",
    community_slug: "programming",
    title: "APIs & System Design",
    description: "REST, HTTP, caching, and designing scalable services.",
    difficulty: "hard",
    minutes: 12,
    coins: 50,
    questions: [
      { id: "q1", type: "mcq", prompt: "HTTP GET should be:", options: ["Idempotent & safe", "Always encrypted only", "Used for passwords in URL", "Same as DELETE"], answer: 0 },
      { id: "q2", type: "true_false", prompt: "REST APIs often use JSON over HTTP.", answer: true },
      { id: "q3", type: "mcq", prompt: "Status 404 means:", options: ["Not found", "Success", "Server error", "Rate limited"], answer: 0 },
      { id: "q4", type: "mcq", prompt: "Rate limiting protects against:", options: ["Abuse and overload", "CSS bugs", "Git merges", "Image formats"], answer: 0 },
      { id: "q5", type: "true_false", prompt: "Microservices split an app into smaller deployable services.", answer: true },
      { id: "q6", type: "multi", prompt: "Caching strategies include:", options: ["CDN edge cache", "Redis", "Deleting all logs daily", "Browser cache headers"], answer: [0, 1, 3] },
      { id: "q7", type: "mcq", prompt: "WebSocket is useful for:", options: ["Real-time bidirectional data", "Static file hosting only", "SQL migrations", "PDF generation"], answer: 0 },
      { id: "q8", type: "mcq", prompt: "API versioning helps:", options: ["Breaking changes without disrupting clients", "Faster CSS", "Remove auth", "Skip tests"], answer: 0 },
    ],
  },
];

export function quizMetaFromBank(id: string) {
  const q = QUIZ_BANK.find((x) => x.id === id);
  if (!q) return null;
  return quizMetaEntry(q);
}

function quizMetaEntry(q: QuizBankEntry) {
  return {
    id: q.id,
    community_slug: q.community_slug,
    title: q.title,
    description: q.description,
    difficulty: q.difficulty,
    questions_count: q.questions.length,
    minutes: q.minutes,
    coins: q.coins,
    created_at: new Date().toISOString(),
  };
}

/** Ordered list for the quizzes page — always real bank entries, never demo placeholders. */
export const QUIZ_BANK_LIST = QUIZ_BANK.map(quizMetaEntry);

export const QUIZ_DIFFICULTY_LABEL: Record<QuizBankEntry["difficulty"], string> = {
  easy: "Easy",
  medium: "Medium",
  hard: "Hard",
};
