/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GigsRouteImport } from './routes/gigs'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as CoinsRouteImport } from './routes/coins'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as QuizzesIdRouteImport } from './routes/quizzes.$id'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as MessagesThreadIdRouteImport } from './routes/messages.$threadId'
import { Route as InternshipsIdRouteImport } from './routes/internships.$id'
import { Route as GigsIdRouteImport } from './routes/gigs.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminQuizzesRouteImport } from './routes/admin.quizzes'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminInternshipsRouteImport } from './routes/admin.internships'
import { Route as AdminInternshipPostingsRouteImport } from './routes/admin.internship-postings'
import { Route as AdminHotRouteImport } from './routes/admin.hot'
import { Route as AdminGigsRouteImport } from './routes/admin.gigs'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCommunitiesRouteImport } from './routes/admin.communities'
import { Route as AdminCoinsRouteImport } from './routes/admin.coins'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicClassVideoRouteImport } from './routes/api/public/class-video'
import { Route as ApiPublicAppConfigRouteImport } from './routes/api/public/app-config'
import { Route as ApiPublicCronRefreshHotRouteImport } from './routes/api/public/cron.refresh-hot'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsRoute = GigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsRoute = CoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizzesRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIdRoute = QuizzesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuizzesRoute,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MessagesRoute,
} as any)
const InternshipsIdRoute = InternshipsIdRouteImport.update({
  id: '/internships/$id',
  path: '/internships/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIdRoute = GigsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GigsRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizzesRoute = AdminQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInternshipsRoute = AdminInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInternshipPostingsRoute = AdminInternshipPostingsRouteImport.update({
  id: '/internship-postings',
  path: '/internship-postings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotRoute = AdminHotRouteImport.update({
  id: '/hot',
  path: '/hot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGigsRoute = AdminGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesRoute = AdminCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoinsRoute = AdminCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClassVideoRoute = ApiPublicClassVideoRouteImport.update({
  id: '/api/public/class-video',
  path: '/api/public/class-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppConfigRoute = ApiPublicAppConfigRouteImport.update({
  id: '/api/public/app-config',
  path: '/api/public/app-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRefreshHotRoute = ApiPublicCronRefreshHotRouteImport.update({
  id: '/api/public/cron/refresh-hot',
  path: '/api/public/cron/refresh-hot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/coins': typeof CoinsRoute
  '/communities': typeof CommunitiesRoute
  '/gigs': typeof GigsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/quizzes': typeof QuizzesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gigs': typeof AdminGigsRoute
  '/admin/hot': typeof AdminHotRoute
  '/admin/internship-postings': typeof AdminInternshipPostingsRoute
  '/admin/internships': typeof AdminInternshipsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/users': typeof AdminUsersRoute
  '/c/$slug': typeof CSlugRoute
  '/courses/$id': typeof CoursesIdRoute
  '/events/$id': typeof EventsIdRoute
  '/gigs/$id': typeof GigsIdRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/p/$id': typeof PIdRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/u/$id': typeof UIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/api/public/app-config': typeof ApiPublicAppConfigRoute
  '/api/public/class-video': typeof ApiPublicClassVideoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/api/public/cron/refresh-hot': typeof ApiPublicCronRefreshHotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/coins': typeof CoinsRoute
  '/communities': typeof CommunitiesRoute
  '/gigs': typeof GigsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gigs': typeof AdminGigsRoute
  '/admin/hot': typeof AdminHotRoute
  '/admin/internship-postings': typeof AdminInternshipPostingsRoute
  '/admin/internships': typeof AdminInternshipsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/users': typeof AdminUsersRoute
  '/c/$slug': typeof CSlugRoute
  '/courses/$id': typeof CoursesIdRoute
  '/events/$id': typeof EventsIdRoute
  '/gigs/$id': typeof GigsIdRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/p/$id': typeof PIdRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/u/$id': typeof UIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/api/public/app-config': typeof ApiPublicAppConfigRoute
  '/api/public/class-video': typeof ApiPublicClassVideoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/api/public/cron/refresh-hot': typeof ApiPublicCronRefreshHotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/coins': typeof CoinsRoute
  '/communities': typeof CommunitiesRoute
  '/gigs': typeof GigsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/quizzes': typeof QuizzesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gigs': typeof AdminGigsRoute
  '/admin/hot': typeof AdminHotRoute
  '/admin/internship-postings': typeof AdminInternshipPostingsRoute
  '/admin/internships': typeof AdminInternshipsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/users': typeof AdminUsersRoute
  '/c/$slug': typeof CSlugRoute
  '/courses/$id': typeof CoursesIdRoute
  '/events/$id': typeof EventsIdRoute
  '/gigs/$id': typeof GigsIdRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/p/$id': typeof PIdRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/u/$id': typeof UIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/api/public/app-config': typeof ApiPublicAppConfigRoute
  '/api/public/class-video': typeof ApiPublicClassVideoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/api/public/cron/refresh-hot': typeof ApiPublicCronRefreshHotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ask'
    | '/coins'
    | '/communities'
    | '/gigs'
    | '/leaderboard'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/quizzes'
    | '/settings'
    | '/terms'
    | '/admin/coins'
    | '/admin/communities'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/gigs'
    | '/admin/hot'
    | '/admin/internship-postings'
    | '/admin/internships'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/posts'
    | '/admin/quizzes'
    | '/admin/users'
    | '/c/$slug'
    | '/courses/$id'
    | '/events/$id'
    | '/gigs/$id'
    | '/internships/$id'
    | '/messages/$threadId'
    | '/p/$id'
    | '/quizzes/$id'
    | '/u/$id'
    | '/admin/'
    | '/courses/'
    | '/quizzes/'
    | '/api/public/app-config'
    | '/api/public/class-video'
    | '/api/public/health'
    | '/api/public/sitemap'
    | '/api/public/cron/refresh-hot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/coins'
    | '/communities'
    | '/gigs'
    | '/leaderboard'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/admin/coins'
    | '/admin/communities'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/gigs'
    | '/admin/hot'
    | '/admin/internship-postings'
    | '/admin/internships'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/posts'
    | '/admin/quizzes'
    | '/admin/users'
    | '/c/$slug'
    | '/courses/$id'
    | '/events/$id'
    | '/gigs/$id'
    | '/internships/$id'
    | '/messages/$threadId'
    | '/p/$id'
    | '/quizzes/$id'
    | '/u/$id'
    | '/admin'
    | '/courses'
    | '/quizzes'
    | '/api/public/app-config'
    | '/api/public/class-video'
    | '/api/public/health'
    | '/api/public/sitemap'
    | '/api/public/cron/refresh-hot'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ask'
    | '/coins'
    | '/communities'
    | '/gigs'
    | '/leaderboard'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/quizzes'
    | '/settings'
    | '/terms'
    | '/admin/coins'
    | '/admin/communities'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/gigs'
    | '/admin/hot'
    | '/admin/internship-postings'
    | '/admin/internships'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/posts'
    | '/admin/quizzes'
    | '/admin/users'
    | '/c/$slug'
    | '/courses/$id'
    | '/events/$id'
    | '/gigs/$id'
    | '/internships/$id'
    | '/messages/$threadId'
    | '/p/$id'
    | '/quizzes/$id'
    | '/u/$id'
    | '/admin/'
    | '/courses/'
    | '/quizzes/'
    | '/api/public/app-config'
    | '/api/public/class-video'
    | '/api/public/health'
    | '/api/public/sitemap'
    | '/api/public/cron/refresh-hot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AskRoute: typeof AskRoute
  CoinsRoute: typeof CoinsRoute
  CommunitiesRoute: typeof CommunitiesRoute
  GigsRoute: typeof GigsRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  QuizzesRoute: typeof QuizzesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  CSlugRoute: typeof CSlugRoute
  CoursesIdRoute: typeof CoursesIdRoute
  EventsIdRoute: typeof EventsIdRoute
  InternshipsIdRoute: typeof InternshipsIdRoute
  PIdRoute: typeof PIdRoute
  UIdRoute: typeof UIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiPublicAppConfigRoute: typeof ApiPublicAppConfigRoute
  ApiPublicClassVideoRoute: typeof ApiPublicClassVideoRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
  ApiPublicCronRefreshHotRoute: typeof ApiPublicCronRefreshHotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs': {
      id: '/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof GigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins': {
      id: '/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof CoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof QuizzesRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$id': {
      id: '/quizzes/$id'
      path: '/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof QuizzesIdRouteImport
      parentRoute: typeof QuizzesRoute
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/internships/$id': {
      id: '/internships/$id'
      path: '/internships/$id'
      fullPath: '/internships/$id'
      preLoaderRoute: typeof InternshipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/$id': {
      id: '/gigs/$id'
      path: '/$id'
      fullPath: '/gigs/$id'
      preLoaderRoute: typeof GigsIdRouteImport
      parentRoute: typeof GigsRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quizzes': {
      id: '/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/internships': {
      id: '/admin/internships'
      path: '/internships'
      fullPath: '/admin/internships'
      preLoaderRoute: typeof AdminInternshipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/internship-postings': {
      id: '/admin/internship-postings'
      path: '/internship-postings'
      fullPath: '/admin/internship-postings'
      preLoaderRoute: typeof AdminInternshipPostingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hot': {
      id: '/admin/hot'
      path: '/hot'
      fullPath: '/admin/hot'
      preLoaderRoute: typeof AdminHotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gigs': {
      id: '/admin/gigs'
      path: '/gigs'
      fullPath: '/admin/gigs'
      preLoaderRoute: typeof AdminGigsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities': {
      id: '/admin/communities'
      path: '/communities'
      fullPath: '/admin/communities'
      preLoaderRoute: typeof AdminCommunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coins': {
      id: '/admin/coins'
      path: '/coins'
      fullPath: '/admin/coins'
      preLoaderRoute: typeof AdminCoinsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/class-video': {
      id: '/api/public/class-video'
      path: '/api/public/class-video'
      fullPath: '/api/public/class-video'
      preLoaderRoute: typeof ApiPublicClassVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-config': {
      id: '/api/public/app-config'
      path: '/api/public/app-config'
      fullPath: '/api/public/app-config'
      preLoaderRoute: typeof ApiPublicAppConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-hot': {
      id: '/api/public/cron/refresh-hot'
      path: '/api/public/cron/refresh-hot'
      fullPath: '/api/public/cron/refresh-hot'
      preLoaderRoute: typeof ApiPublicCronRefreshHotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCoinsRoute: typeof AdminCoinsRoute
  AdminCommunitiesRoute: typeof AdminCommunitiesRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGigsRoute: typeof AdminGigsRoute
  AdminHotRoute: typeof AdminHotRoute
  AdminInternshipPostingsRoute: typeof AdminInternshipPostingsRoute
  AdminInternshipsRoute: typeof AdminInternshipsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminQuizzesRoute: typeof AdminQuizzesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoinsRoute: AdminCoinsRoute,
  AdminCommunitiesRoute: AdminCommunitiesRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGigsRoute: AdminGigsRoute,
  AdminHotRoute: AdminHotRoute,
  AdminInternshipPostingsRoute: AdminInternshipPostingsRoute,
  AdminInternshipsRoute: AdminInternshipsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminQuizzesRoute: AdminQuizzesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GigsRouteChildren {
  GigsIdRoute: typeof GigsIdRoute
}

const GigsRouteChildren: GigsRouteChildren = {
  GigsIdRoute: GigsIdRoute,
}

const GigsRouteWithChildren = GigsRoute._addFileChildren(GigsRouteChildren)

interface MessagesRouteChildren {
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesThreadIdRoute: MessagesThreadIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface QuizzesRouteChildren {
  QuizzesIdRoute: typeof QuizzesIdRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
}

const QuizzesRouteChildren: QuizzesRouteChildren = {
  QuizzesIdRoute: QuizzesIdRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
}

const QuizzesRouteWithChildren =
  QuizzesRoute._addFileChildren(QuizzesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AskRoute: AskRoute,
  CoinsRoute: CoinsRoute,
  CommunitiesRoute: CommunitiesRoute,
  GigsRoute: GigsRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  QuizzesRoute: QuizzesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  CSlugRoute: CSlugRoute,
  CoursesIdRoute: CoursesIdRoute,
  EventsIdRoute: EventsIdRoute,
  InternshipsIdRoute: InternshipsIdRoute,
  PIdRoute: PIdRoute,
  UIdRoute: UIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiPublicAppConfigRoute: ApiPublicAppConfigRoute,
  ApiPublicClassVideoRoute: ApiPublicClassVideoRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
  ApiPublicCronRefreshHotRoute: ApiPublicCronRefreshHotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
